// Generated by CoffeeScript 1.10.0

/*

Supported Client Requests
----------------
SUBMIT_JOB
SUBMIT_JOB_LOW
SUBMIT_JOB_HIGH

    A client issues one of these when a job needs to be run. The
    server will then assign a job handle and respond with a JOB_CREATED
    packet.

    If on of the BG versions is used, the client is not updated with
    status or notified when the job has completed (it is detached).

    The Gearman job server queue is implemented with three levels:
    normal, high, and low. Jobs submitted with one of the HIGH versions
    always take precedence, and jobs submitted with the normal versions
    take precedence over the LOW versions.

    Arguments:
    - NULL byte terminated function name.
    - NULL byte terminated unique ID.
    - Opaque data that is given to the function as an argument.

GET_STATUS (TODO)

    A client issues this to get status information for a submitted job.

    Arguments:
    - Job handle that was given in JOB_CREATED packet.


    A client issues this to set an option for the connection in the
    job server. Returns a OPTION_RES packet on success, or an ERROR
    packet on failure.

Unsupported client requests:
SUBMIT_JOB_BG
SUBMIT_JOB_LOW_BG
SUBMIT_JOB_HIGH_BG
SUBMIT_JOB_SCHED ("not used")
SUBMIT_JOB_EPOCH ("not used")
OPTION_REQ

Supported Responses to Client
----------------
JOB_CREATED

    This is sent in response to one of the SUBMIT_JOB* packets. It
    signifies to the client that a the server successfully received
    the job and queued it to be run by a worker.

    Arguments:
    - Job handle assigned by server.

WORK_DATA, WORK_WARNING, WORK_STATUS, WORK_COMPLETE, WORK_FAIL

    For non-background jobs, the server forwards these packets from
    the worker to clients. See "Worker Requests" for more information
    and arguments.

STATUS_RES (TODO)

    This is sent in response to a GET_STATUS request. This is used by
    clients that have submitted a job with SUBMIT_JOB_BG to see if the
    job has been completed, and if not, to get the percentage complete.

    Arguments:
    - NULL byte terminated job handle.
    - NULL byte terminated known status, this is 0 (false) or 1 (true).
    - NULL byte terminated running status, this is 0 (false) or 1
      (true).
    - NULL byte terminated percent complete numerator.
    - Percent complete denominator.

Unsupported responses to client:
WORK_EXCEPTION (deprecated)
OPTION_RES
 */

(function() {
  var Client, EventEmitter, Gearman, _,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Gearman = require('./gearman');

  _ = require('underscore');

  EventEmitter = require("events").EventEmitter;

  Client = (function(superClass) {
    extend(Client, superClass);

    function Client(options) {
      this.options = options;
      this.submitHighJob = bind(this.submitHighJob, this);
      this.submitJob = bind(this.submitJob, this);
      this.queue = [];
      this.options = _.defaults(this.options || {}, {
        host: 'localhost',
        port: 4730,
        debug: false
      });
      Client.__super__.constructor.call(this, this.options.host, this.options.port, this.options.debug);
      this.jobs = {};
      this.on('JOB_CREATED', (function(_this) {
        return function(handle) {
          var job;
          job = _this.queue.shift();
          _this.jobs[handle] = job;
          return job.emit('created', handle);
        };
      })(this));
      this.on('WORK_DATA', (function(_this) {
        return function(handle, data) {
          return _this.jobs[handle].emit('data', handle, "" + data);
        };
      })(this));
      this.on('WORK_WARNING', (function(_this) {
        return function(handle, warning) {
          return _this.jobs[handle].emit('warning', handle, "" + warning);
        };
      })(this));
      this.on('WORK_STATUS', (function(_this) {
        return function(handle, num, den) {
          return _this.jobs[handle].emit('status', handle, num, den);
        };
      })(this));
      this.on('WORK_COMPLETE', (function(_this) {
        return function(handle, data) {
          _this.jobs[handle].emit('complete', handle, data);
          return delete _this.jobs[handle];
        };
      })(this));
      this.on('WORK_FAIL', (function(_this) {
        return function(handle) {
          handle = handle.replace(/\0/g, '');
          _this.jobs[handle].emit('fail', handle);
          return delete _this.jobs[handle];
        };
      })(this));
      this.connect();
    }

    Client.prototype.submitJob = function(name, payload) {
      var job;
      job = new EventEmitter;
      this.queue.push(job);
      this.sendCommand("SUBMIT_JOB", name, false, payload);
      return job;
    };

    Client.prototype.submitHighJob = function(name, payload) {
      var job;
      job = new EventEmitter;
      this.queue.push(job);
      this.sendCommand("SUBMIT_JOB_HIGH", name, false, payload);
      return job;
    };

    return Client;

  })(Gearman);

  module.exports = Client;

}).call(this);
